# Generated by Django 4.2.2 on 2023-06-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст собщения')),
            ],
        ),
    ]
